# Generated by Django 5.0.7 on 2024-08-05 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quiz",
            options={"verbose_name_plural": "Quizzes"},
        ),
    ]
